In [1]:
import numpy as np

In [2]:
n1=np.array([10,20,30])
n1

array([10, 20, 30])

In [3]:
n2=np.array([[1,2,3],[4,5,6]])
n2

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
n3=np.zeros((1,2))
n3

array([[0., 0.]])

In [5]:
n4=np.zeros((2,4))
n4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
n5=np.ones((3,5))
n5

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
n6=np.ones(5)
n6

array([1., 1., 1., 1., 1.])

In [8]:
n7=np.full((2,4),5)
n7

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

In [10]:
n8=np.arange(10,30)
n8

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [11]:
n9=np.arange(10,30,5)
n9

array([10, 15, 20, 25])

In [17]:
n10=np.random.randint(10)
n10

6

In [19]:
n11=np.random.randint(1,100,5)
n11

array([21,  8, 60, 55, 41])

In [20]:
n12=np.random.rand(5)
n12

array([0.40976464, 0.69472861, 0.17007989, 0.56531126, 0.22372143])

In [24]:
n13=np.array([[1,2,3],[4,5,6]])
n13.shape

(2, 3)

In [25]:
n13.shape=(3,2)
n13

array([[1, 2],
       [3, 4],
       [5, 6]])

In [27]:
#joining arrays
n14=np.array([1,2,3])
n15=np.array([4,5,6])
print(n14)
print(n15)

[1 2 3]
[4 5 6]


In [28]:
#vstack-verical stack->vertically joins array
np.vstack((n14,n15))

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
#hstack-horizonal stack->horizontally joins array
np.hstack((n14,n15))

array([1, 2, 3, 4, 5, 6])

In [30]:
#column_stack->joins array with columns
np.column_stack((n14,n15))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [32]:
n16=np.array([1,2,3,4,5,6])
n17=np.array([4,5,6,7,8,9])
print(n16)
print(n17)

[1 2 3 4 5 6]
[4 5 6 7 8 9]


In [35]:
np.union1d(n16,n17)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
np.intersect1d(n16,n17)

array([4, 5, 6])

In [37]:
np.setdiff1d(n16,n17)

array([1, 2, 3])

In [38]:
np.setdiff1d(n17,n16)

array([7, 8, 9])

In [40]:
np.sum([n16,n17])

60

In [43]:
np.sum([n16,n17],axis=1)

array([21, 39])

In [53]:
n18=np.array([10,20,30,40])
n18

array([10, 20, 30, 40])

In [54]:
n18=n18+5 #perform +-*/
n18

array([15, 25, 35, 45])

In [55]:
np.mean(n18)

30.0

In [56]:
np.std(n18)

11.180339887498949

In [57]:
np.median(n18)

30.0