In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

In [13]:
df=pd.read_csv('mlr.csv')
df

X1  X2     y
0   3   8  -3.7
1   4   5   3.5
2   5   7   2.5
3   6   3  11.5
4   2   1   5.7

In [16]:
x=df[['X1','X2']]
x

X1  X2
0   3   8
1   4   5
2   5   7
3   6   3
4   2   1

In [17]:
y=df[['y']]
y

y
0  -3.7
1   3.5
2   2.5
3  11.5
4   5.7

In [18]:
model=LinearRegression()

In [19]:
model.fit(x,y)

LinearRegression()

In [20]:
model.coef_

array([[ 2.28163009, -1.67210031]])

In [21]:
model.intercept_

array([2.79956113])

In [11]:
#Mutiple regreesion model for house price prediction y=137.25*area-26025.*bedrooms-6825.*age+383725.

In [23]:
model.predict([[8,5]])

array([[12.69210031]])

In [24]:
model.predict([[5,8]])

array([[0.83090909]])

In [25]:
sklearn_ypredict=model.predict(x)
sklearn_ypredict

array([[-3.7323511 ],
       [ 3.56557994],
       [ 2.5030094 ],
       [11.47304075],
       [ 5.690721  ]])